# Generated by Django 3.1.7 on 2021-05-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('StandardApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwishlist',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardApps.clients'),
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardApps.produits'),
        ),
    ]
