# Generated by Django 4.0.2 on 2022-02-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StandardApps', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwishlist',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardApps.clients'),
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardApps.produits'),
        ),
        migrations.AddField(
            model_name='clientenquirymessage',
            name='enquirySujet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.enquirymessagesujet'),
        ),
    ]
