# Generated by Django 3.1.7 on 2021-05-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210518_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryMessageSujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('sujet', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEnquiryMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('sujet', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('imageMessage', models.ImageField(upload_to='MessageEnquiry')),
                ('enquirySujet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.enquirymessagesujet')),
            ],
        ),
    ]
