# Generated by Django 3.1.7 on 2021-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_clientenquirymessage_enquirymessagesujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientenquirymessage',
            name='slug',
            field=models.SlugField(),
        ),
    ]
