# Generated by Django 3.1.7 on 2021-05-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApps', '0004_category_descriptioncategory'),
        ('chat', '0003_vendeurmessages_produit_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmessages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendeurmessages',
            name='user',
        ),
        migrations.AddField(
            model_name='clientmessages',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StandardApps.clients'),
        ),
        migrations.AddField(
            model_name='vendeurmessages',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StandardApps.vendeurs'),
        ),
    ]
