# Generated by Django 3.1.7 on 2021-05-23 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApps', '0004_category_descriptioncategory'),
        ('chat', '0004_auto_20210523_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeurmessages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StandardApps.clients'),
        ),
    ]
