# Generated by Django 4.0.2 on 2022-02-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StandardApps', '0001_initial'),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpolitique',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StandardApps.vendeurs'),
        ),
        migrations.AddField(
            model_name='vendeurbusiness',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StandardApps.vendeurs'),
        ),
    ]
