# Generated by Django 3.1.7 on 2021-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeurs',
            name='businessProfile',
            field=models.BooleanField(default=False),
        ),
    ]
