# Generated by Django 3.1.7 on 2021-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApps', '0002_vendeurs_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageCategory',
            field=models.ImageField(blank=True, null=True, upload_to='categoryImage'),
        ),
    ]
