# Generated by Django 3.1.7 on 2021-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApps', '0003_category_imagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptionCategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
