# Generated by Django 3.1.7 on 2021-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApps', '0004_category_descriptioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
